version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: iam_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iam-network

volumes:
  postgres_data:

networks:
  iam-network:
    driver: bridge
