version: "3.8"
services:
  iam-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d1qspffdiees73f9ihkg-a.oregon-postgres.render.com:5432/taskdb_waej
      SPRING_DATASOURCE_USERNAME: taskdb_waej_user
      SPRING_DATASOURCE_PASSWORD: 8yPg3XF2RTMR0w92GHA1JvnTsCRynDMb
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 8081
